addSbtPlugin("org.scalariform" % "sbt-scalariform" % "1.8.3")
addSbtPlugin("com.github.sbt"  % "sbt-pgp"         % "2.2.1")
addSbtPlugin("com.github.sbt"  % "sbt-release"     % "1.4.0")
addSbtPlugin("com.eed3si9n"    % "sbt-buildinfo"   % "0.13.1")
addSbtPlugin("org.xerial.sbt"  % "sbt-sonatype"    % "3.9.12")
